### ISSUE TITLE
백엔드 #1 관련

### ISSUE THREAD

**Issue by mswgen** [Team-int/interview_task#5]
추가점수에 이런건 어떨까요?

> DB에 대한 엑세스 권한이 있어도 비번을 알 수 없다(+2점)

~~@chul0721~~

**Comment by chul0721** [comment]
확인되었습니다.

**Comment by chul0721** [comment]
처리 완료 후 해당 이슈를 닫겠습니다.

**Comment by MadeGOD** [comment]
완료 제한을 해주셔서 감사합니다.
